import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import ReduxProvider from "./redux/Provider";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ReduxProvider>
          <nav className="bg-slate-200 p-5 text-slate-600">
            <Link href="/" className="text-lg font-semibold ">
              Note App
            </Link>
          </nav>
          {children}
        </ReduxProvider>
      </body>
    </html>
  );
}
